name: vikrant
on:
  
 push:
  branches: [ "master" ]
 pull_request:
  branches: [ "master" ]
 workflow_dispatch:
jobs:
 job1:
  runs-on: self-hosted
  steps:
   - uses: actions/checkout@v3
   - name: this first job
     run: echo Hello, world!
